# Generated by Django 3.2 on 2021-05-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_login_id', models.CharField(blank=True, max_length=50)),
                ('userid', models.CharField(max_length=64, verbose_name='사용자아이디')),
                ('name', models.CharField(max_length=64, verbose_name='사용자명')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('email', models.CharField(max_length=64, verbose_name='이메일')),
                ('registerd_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
        ),
    ]
